### ISSUE TITLE
读写csv文件和列表展示

### ISSUE THREAD

**Issue by lwx294821** [lwx294821/Garage#2]
页面表单输入保存到csv文件，前端展示文件内容

@xwx379731

**Comment by xwx379731** [comment]
https://www.cnblogs.com/chrischennx/p/5119608.html
包下载：http://sourceforge.net/projects/opencsv/files/latest/download

**Comment by xwx379731** [comment]
包：
http://commons.apache.org/proper/commons-dbcp/download_dbcp.cgi
http://commons.apache.org/proper/commons-pool/download_pool.cgi
配置：
http://blog.csdn.net/hu_shengyang/article/details/7900481
@lwx294821

**Comment by xwx379731** [comment]
<dependency>
    <groupId>commons-dbcp</groupId>
    <artifactId>commons-dbcp</artifactId>
    <version>1.4</version>
</dependency>

<dependency>
    <groupId>commons-pool</groupId>
    <artifactId>commons-pool</artifactId>
    <version>1.6</version>
</dependency>

**Comment by xwx379731** [comment]
<div class="btn-group open" style="width: 150px;">
    <button type="button" class="multiselect dropdown-toggle btn btn-xs btn-default"
            data-toggle="dropdown" title="Patch;Documentation;CodeSecurityIssues;Question;Operations"
            style="width: 150px;">Label<span class="caret"></span>
    </button>
    <ul class="multiselect-container dropdown-menu pull-right"
        style="max-height: 312px; overflow-y: auto; overflow-x: hidden; width: 200%;">
        <li class="multiselect-item filter" value="0">
            <div class="input-group">
                                            <span class="input-group-addon">
                                            <i class="glyphicon glyphicon-search"></i>
                                        </span>
                <input class="form-control multiselect-search" type="text" placeholder="Search">
            </div>
        </li>
        <li class="active"><a href="javascript:void(0);">
            <label class="checkbox"><input type="checkbox" value="Patch">
                <span title="Patch" class="tab labelstyle-fc2929">Patch
                                        </span>
            </label>
        </a>
        </li>
        <li class="active"><a href="javascript:void(0);">
            <label class="checkbox">
                <input type="checkbox" value="Documentation">
                <span title="Documentation" class="tab labelstyle-84b6eb">
                                                Documentation
                                            </span>
            </label>
        </a>
        </li>
        <li class="active">
            <a href="javascript:void(0);">
                <label class="checkbox">
                    <input type="checkbox" value="Code Security Issues">
                    <span title="Code Security Issues" class="tab labelstyle-e102d8">
                                                    Code Security Issues
                                                </span>
                </label>
            </a>
        </li>
        <li class="active">
            <a href="javascript:void(0);">
                <label class="checkbox">
                    <input type="checkbox" value="Question">
                    <span title="Question" class="tab labelstyle-e102d8">
                                                    Question
                                                </span>
                </label>
            </a>
        </li>
        <li class="active">
            <a href="javascript:void(0);">
                <label class="checkbox">
                    <input type="checkbox" value="Operations">
                    <span title="Operations" class="tab labelstyle-0b02e1">
                                                    Operations
                                                </span>
                </label>
            </a>
        </li>
    </ul>
</div>
